apiVersion: eidolon/v1
kind: Machine
spec:
  file_memory:
    implementation: "LocalFileMemory"
    root_dir: "${EIDOLON_DATA_DIR}/code_search/file_memory"
  symbolic_memory:
    implementation: "MongoSymbolicMemory"
    mongo_database_name: "eidolon"
  similarity_memory:
    vector_store:
      implementation: "ChromaVectorStore"
      url: "file://${EIDOLON_DATA_DIR}/doc_producer"
    embedder:
      implementation: "OpenAIEmbedding"
