apiVersion: eidolon/v1
kind: Machine
spec:
  file_memory:
    implementation: "eidos_sdk.memory.local_file_memory.LocalFileMemory"
    root_dir: "${EIDOLON_DATA_DIR}/code_search/file_memory"
  symbolic_memory:
    implementation: "eidos_sdk.memory.mongo_symbolic_memory.MongoSymbolicMemory"
    mongo_database_name: "eidolon"
  similarity_memory:
    vector_store:
      implementation: "eidos_sdk.memory.chroma_vector_store.ChromaVectorStore"
      url: "file://${EIDOLON_DATA_DIR}/code_search"