apiVersion: eidolon/v1
kind: Machine
spec:
  file_memory:
    implementation: "eidos_sdk.memory.local_file_memory.LocalFileMemory"
    spec:
      root_dir: "${EIDOLON_DATA_DIR}/code_search/file_memory"
  symbolic_memory:
    implementation: "eidos_sdk.memory.mongo_symbolic_memory.MongoSymbolicMemory"
    spec:
      mongo_database_name: "eidolon"
  similarity_memory:
      implementation: "eidos_sdk.memory.chroma_vector_store.ChromaVectorMemory"
      spec:
        url: "file://${EIDOLON_DATA_DIR}/doc_producer"