apiVersion: eidolon/v1
kind: Machine

metadata:
  name: local_dev

spec:
  symbolic_memory: LocalSymbolicMemory
  file_memory:
    implementation: LocalFileMemory
    root_dir: "/tmp/eidos/file_memory"
  similarity_memory:
    implementation: SimilarityMemory
    embedder: eidos_sdk.memory.embeddings.NoopEmbedding
    vector_store: eidos_sdk.memory.noop_memory.NoopVectorStore
