apiVersion: eidolon/v1
kind: Machine
spec:
  file_memory:
    implementation: "eidos_sdk.memory.local_file_memory.LocalFileMemory"
    spec:
      root_dir: "/tmp/hello_world"
  symbolic_memory:
    implementation: "eidos_sdk.memory.mongo_symbolic_memory.MongoSymbolicMemory"
    spec:
      mongo_database_name: "eidolon"
