on:
  push:
    branches: [main]
  pull_request:

jobs:
  cli-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
        working-directory: cli
      - run: poetry run ruff format .
        working-directory: cli
      - run: poetry run ruff check .
        working-directory: cli
      - run: poetry run pytest
        working-directory: cli

  examples-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
        working-directory: examples
      - run: poetry run ruff format .
        working-directory: examples
      - run: poetry run ruff check .
        working-directory: examples
      - run: poetry run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: examples

  sdk-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
        working-directory: sdk
      - run: poetry run ruff format .
        working-directory: sdk
      - run: poetry run ruff check .
        working-directory: sdk
      - run: poetry run pytest
        env:
          OPENAI_API_KEY: intentionally_unused
        working-directory: sdk
