name: Build and Push Docker Image
on:
  workflow_run:
    workflows: [ "Bump SDK Version" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install
        working-directory: sdk
      - run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry version patch
          poetry publish --build
          echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV
        working-directory: sdk
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version and publish to PyPI"
          tagging_message: v${{ env.VERSION }}

  docker:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make push_image
        working-directory: sdk
